{% set name = "planetmapper" %}
{% set version = "1.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/planetmapper-{{ version }}.tar.gz
  sha256: fa1647de939d555824556f6d2de7ed0f913912ed6a3a178030dfe06518fdf390

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - planetmapper = planetmapper:main

requirements:
  host:
    - python >=3.10
    - pip
  run:
    - python >=3.10
    - astropy
    - matplotlib-base
    - numpy
    - pillow
    - spiceypy
    - scipy
    - photutils
    - tqdm
    - pyproj
    - typing-extensions

test:
  imports:
    - planetmapper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ortk95/planetmapper
  summary: 'PlanetMapper: A Python module for visualising, navigating and mapping Solar System observations'
  license: MIT
  license_file: LICENSE.txt
  doc_url: https://planetmapper.readthedocs.io/
  dev_url: https://github.com/ortk95/planetmapper

extra:
  recipe-maintainers:
    - ortk95
